#!/bin/bash
curdir=$(realpath $(dirname $0))
cache_dir="${curdir}/../cache"
json="latest_flotilla_source_2.json"
full_path_json="${cache_dir}/${json}"

if [ $(find ${cache_dir} -type f -name "${json}" -newermt '-15 seconds' | wc -l) = "1" ]
then
	echo "data already fetched"
	exit 1
fi
echo fetching

#curl 'https://livetrack.garmin.com/apollo/graphql' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://live.garmin.com/' -H 'Content-Type: application/json' -H 'authorization: ' -H 'garmin-guid: ' -H 'Origin: https://live.garmin.com' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Priority: u=4' -H 'TE: trailers' --data-raw '{"query":"\n                    query getTrackPoints($sessionId: String!, $token: String!, $disablePolling: Boolean) {\n                        trackPointsBySessionId(\n                            sessionId: $sessionId\n                            token: $token\n                            limit: 3000\n                            disablePolling: $disablePolling\n                        ) {\n                            trackPoints {\n                                fitnessPointData {\n                                    totalDurationSecs\n                                    speedMetersPerSec\n                                    totalDistanceMeters\n                                    activityType\n                                    cadenceCyclesPerMin\n                                    distanceMeters\n                                    durationSecs\n                                    elevationGainMeters\n                                    elevationSource\n                                    elevation\n                                    eventTypes\n                                    heartRateBeatsPerMin\n                                    pointStatus\n                                    powerWatts\n                                    speedMetersPerSec\n                                }\n                                position {\n                                    lat\n                                    lon\n                                }\n                                dateTime\n                                speed\n                            }\n                            sessionId\n                        }\n                    }\n                ","variables":{"sessionId":"e162481b-5edc-800e-a915-dbc858405701","token":"11A26E3BB58A3E22459C99D6B2E5E5D","disablePolling":true},"operationName":"getTrackPoints"}' | tee "${full_path_json}"


curl 'https://livetrack.garmin.com/apollo/graphql' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Referer: https://live.garmin.com/' -H 'Content-Type: application/json' -H 'authorization: ' -H 'garmin-guid: ' -H 'Origin: https://live.garmin.com' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Priority: u=4' -H 'TE: trailers' --data-raw '{"query":"\n                    query getTrackPoints($sessionId: String!, $token: String!, $disablePolling: Boolean) {\n                        trackPointsBySessionId(\n                            sessionId: $sessionId\n                            token: $token\n                            limit: 3000\n                            disablePolling: $disablePolling\n                        ) {\n                            trackPoints {\n                                fitnessPointData {\n                                    totalDurationSecs\n                                    speedMetersPerSec\n                                    totalDistanceMeters\n                                    activityType\n                                    cadenceCyclesPerMin\n                                    distanceMeters\n                                    durationSecs\n                                    elevationGainMeters\n                                    elevationSource\n                                    elevation\n                                    eventTypes\n                                    heartRateBeatsPerMin\n                                    pointStatus\n                                    powerWatts\n                                    speedMetersPerSec\n                                }\n                                position {\n                                    lat\n                                    lon\n                                }\n                                dateTime\n                                speed\n                            }\n                            sessionId\n                        }\n                    }\n                ","variables":{"sessionId":"b2e08860-265e-8540-9877-8a235f2aa201","token":"9219F8EFFEADE8C2F2431E7E4EB3BCE4","disablePolling":true},"operationName":"getTrackPoints"}' | tee "${full_path_json}"



#curl 'https://livetrack.garmin.com/apollo/graphql' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:138.0) Gecko/20100101 Firefox/138.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: https://live.garmin.com/' -H 'Content-Type: application/json' -H 'authorization: ' -H 'garmin-guid: ' -H 'Origin: https://live.garmin.com' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-site' -H 'Priority: u=4' -H 'TE: trailers' --data-raw '{"query":"\n                    query getTrackPoints($sessionId: String!, $token: String!, $disablePolling: Boolean) {\n                        trackPointsBySessionId(\n                            sessionId: $sessionId\n                            token: $token\n                            limit: 3000\n                            disablePolling: $disablePolling\n                        ) {\n                            trackPoints {\n                                fitnessPointData {\n                                    totalDurationSecs\n                                    speedMetersPerSec\n                                    totalDistanceMeters\n                                    activityType\n                                    cadenceCyclesPerMin\n                                    distanceMeters\n                                    durationSecs\n                                    elevationGainMeters\n                                    elevationSource\n                                    elevation\n                                    eventTypes\n                                    heartRateBeatsPerMin\n                                    pointStatus\n                                    powerWatts\n                                    speedMetersPerSec\n                                }\n                                position {\n                                    lat\n                                    lon\n                                }\n                                dateTime\n                                speed\n                            }\n                            sessionId\n                        }\n                    }\n                ","variables":{"sessionId":"e162481b-5edc-800e-a915-dbc858405701","token":"11A26E3BB58A3E22459C99D6B2E5E5D","disablePolling":true},"operationName":"getTrackPoints"}' | tee "${full_path_json}"
